name: ai_701
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - comm=0.1.4
  - curl=8.4.0
  - cython=3.0.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - expat=2.5.0
  - gdbm=1.18
  - gettext=0.21.0
  - git=2.40.1
  - icu=73.1
  - ipykernel=6.26.0
  - ipython=8.17.2
  - jedi=0.19.1
  - jupyter_client=7.3.4
  - jupyter_core=5.5.0
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libcurl=8.4.0
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.57.0
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libxml2=2.10.4
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=3.0.12
  - packaging=23.2
  - parso=0.8.3
  - pcre2=10.42
  - perl=5.34.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - platformdirs=4.0.0
  - prompt-toolkit=3.0.41
  - prompt_toolkit=3.0.41
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=25.1.0
  - readline=8.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.13.0
  - typing_extensions=4.8.0
  - wcwidth=0.2.10
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - absl-py==2.0.0
    - appdirs==1.4.4
    - astunparse==1.6.3
    - blosc2==2.3.1
    - cachetools==5.3.2
    - certifi==2023.7.22
    - chardet==4.0.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - contourpy==1.2.0
    - cycler==0.10.0
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - filelock==3.13.1
    - flatbuffers==23.5.26
    - fonttools==4.44.3
    - fsspec==2023.10.0
    - gast==0.5.4
    - gitdb==4.0.11
    - gitpython==3.1.40
    - google-auth==2.23.4
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.59.2
    - h5py==3.10.0
    - hdf5storage==0.1.19
    - idna==2.10
    - imbalanced-learn==0.11.0
    - imblearn==0.0
    - importlib-metadata==6.8.0
    - importlib-resources==6.1.1
    - jinja2==3.1.2
    - joblib==1.3.2
    - keras==2.14.0
    - kiwisolver==1.4.5
    - libclang==16.0.6
    - markdown==3.5.1
    - markupsafe==2.1.3
    - mat73==0.62
    - matplotlib==3.8.2
    - ml-dtypes==0.2.0
    - mpmath==1.3.0
    - msgpack==1.0.7
    - ndindex==1.7
    - networkx==3.2.1
    - numexpr==2.8.7
    - numpy==1.26.2
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvcc-cu11==11.8.89
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.7.0.84
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu11==2.16.5
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.101
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - opencv-python==4.8.1.78
    - opencv-python-headless==4.8.0.74
    - opt-einsum==3.3.0
    - pandas==2.1.3
    - pillow==10.1.0
    - pip==23.3.1
    - pipreqs==0.4.13
    - protobuf==4.25.0
    - py-cpuinfo==9.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pyparsing==2.4.7
    - python-dotenv==1.0.0
    - python-graphviz==0.20.1
    - python-magic==0.4.27
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - requests-toolbelt==1.0.0
    - roboflow==1.1.9
    - rsa==4.9
    - scikit-learn==1.3.2
    - scipy==1.11.4
    - sentry-sdk==1.36.0
    - setproctitle==1.3.3
    - setuptools==69.0.2
    - sklearn==0.0.post11
    - smmap==5.0.1
    - supervision==0.16.0
    - sympy==1.12
    - tables==3.9.1
    - tensorboard==2.14.1
    - tensorboard-data-server==0.7.2
    - tensorflow==2.14.0
    - tensorflow-estimator==2.14.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - tensorrt==8.5.3.1
    - termcolor==2.3.0
    - threadpoolctl==3.2.0
    - torch==2.1.1
    - torchinfo==1.8.0
    - torchvision==0.16.1
    - torchviz==0.0.2
    - tqdm==4.66.1
    - triton==2.1.0
    - tzdata==2023.3
    - urllib3==2.1.0
    - wandb==0.16.0
    - werkzeug==3.0.1
    - wrapt==1.14.1
    - yarg==0.1.9
    - zipp==3.17.0