name: mini_tuning
entity: turtle_detection
program: main.py
method: bayes
metric:
  goal: maximize
  name: eval/f1
parameters:
  epochs:
    value: 20
  batch_size:
    values: [64, 128]  
  lr:
    min: 0.008
    max: 0.035