name: mini_tuning_root
entity: turtle_detection
program: main.py
command:
method: bayes
metric:
  goal: maximize
  name: eval/f1
parameters:
  enable_aug_rhf:
    value: True
  enable_aug_rvf:
    value: True
  enable_aug_rr:
    value: False
  enable_ins_weights:
    value: False
  enable_root_weights:
    value: True
  epochs:
    values: [15, 20, 25]
  batch_size:
    values: [64, 128]  
  lr:
    min: 0.008
    max: 0.035