name: lr_tunning
entity: evhenia-k-you
program: main.py
method: bayes
metric:
  goal: maximize
  name: eval/f1
parameters:
  epochs:
    values: [10, 20, 30]
  batch_size:
    values: [64, 128]  
  lr:
    min: 0.007
    max: 0.05
  label_smoothing:
    min: 0.1
    max: 0.3